ise:
  nodename: 'PXGRID-NODENAME'
  description: 'Development Host'
  password: ''
  pxgridhostname: 'ISE-HOSTNAME-OR-IP'
  pxclient_cert: 'certs/client_cert.cer'
  pxclient_key: 'certs/client_cert.key'
  pxclient_pass: 'Cisco12345'
  pxclient_ca: 'certs/CertificateServicesRootCA.cer'
  iseroot_ca: 'certs/ROOTCA-CA.cer'
